# Generated by Django 4.2.3 on 2023-07-24 17:17

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('image', models.ImageField(blank=True, upload_to=organizations.models.path_and_rename_fundraise)),
                ('state', models.CharField(choices=[('ongoing', 'ongoing'), ('finished', 'finished')], max_length=8)),
            ],
        ),
    ]
