# Generated by Django 4.2.3 on 2023-07-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_fundraise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraise',
            name='current_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraise',
            name='target_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
