# Generated by Django 4.2.3 on 2023-07-24 17:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_fundraise_current_amount_fundraise_target_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 7, 24, 17, 39, 33, 154853, tzinfo=datetime.timezone.utc))),
                ('tokens_amount', models.PositiveIntegerField()),
                ('currency_code', models.CharField(max_length=3)),
                ('money_amount', models.PositiveIntegerField()),
                ('fundraise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.fundraise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
