# Generated by Django 4.2.3 on 2023-07-24 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 17, 39, 36, 414257, tzinfo=datetime.timezone.utc)),
        ),
    ]
